model:
  type: catboost
  params:
    iterations: 1000
    learning_rate: 0.05
    depth: 6
    eval_metric: AUC
    early_stopping_rounds: 50
    verbose: 100

data:
  raw_path: "Sparkov_Data_Generation/parquet_historical"
  processed_path: "Sparkov_Data_Generation/processed"
  test_data_path: "old_csv_Data"

threshold:
  method: "time_series_cv"
  n_folds: 3

mlflow:
  experiment_name: "fraud_detection_pipeline"
  tracking_uri: "databricks"
